const starterDecks = [
  {
    name: "True Knight",
    maxHP: 100,
    gold: 150,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new BasicSpear(),
      new BasicBow(),
      new BasicAxe(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
    ],
    relics: ["Scroll of Knowledge"],
  },
  {
    name: "Tank Knight",
    maxHP: 120,
    gold: 120,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new BasicSword(),
      new BasicSword(),
      new Hammer(),
      new TowerShield(),
      new TowerShield(),
      new TowerShield(),
      new TowerShield(),
    ],
    relics: ["Bramble Mantle"],
  },
  {
    name: "Poison Knight",
    maxHP: 90,
    gold: 180,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new BrokenBlade(),
      new PoisonArrow(),
      new PoisonDagger(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
    ],
    relics: ["Curse of the plague"],
  },
  {
    name: "Holy Knight",
    maxHP: 100,
    gold: 125,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new Crossbow(),
      new BigBlade(),
      new Bomb(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
      new MasterShield(),
    ],
    relics: ["Pacifist Amulett"],
  },
  {
    name: "Berserker",
    maxHP: 110,
    gold: 100,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new BerserkersBlade(),
      new BerserkersSpear(),
      new RageAxe(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
    ],
    relics: ["Enrage"],
  },
  {
    name: "Medic",
    maxHP: 110,
    gold: 130,
    weapons: [
      new Dagger(),
      new Dagger(),
      new Dagger(),
      new ThrowingKnife(),
      new BigHealthPotion(),
      new Leechfang(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
    ],
    relics: ["Untouched Heart"],
  },
  {
    name: "Golden Knight",
    maxHP: 80,
    gold: 200,
    weapons: [
      new BasicSword(),
      new BasicSword(),
      new BasicSword(),
      new GoldSword(),
      new GoldenPotion(),
      new BasicShield(),
      new BasicShield(),
      new BasicShield(),
      new GoldShield(),
    ],
    relics: ["Golden Sigil"],
  },
  {
    name: "Custom Knight",
    maxHP: 100,
    gold: 150,
    weapons: [],
    relics: [],
  },
];
